# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: devise_dev
  username: postgres
  password: postgres
  host: localhost
test:
  <<: *default
  database: devise_test
  username: postgres
  password: postgres
  host: localhost
production:
  <<: *default
  database: devise_prod
  # username: deploy